name: Test, build and deploy to Pantheon

on:
  push:
    branches-ignore:
      # Trigger on push to any branch besides master
      - master

  workflow_dispatch:

env:
  SOME_ENV_VAR: "haha"
jobs:
  # First way: uploading and downloading artifacts.
  artifacts-1:
    name: Artifacts 1
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{secrets.GITHUB_TOKEN}}
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set some variables
        run: |
          echo SITE_URL=hehehe >> $GITHUB_ENV
          echo SITE_URL=hehehe > .env
          ls -la
      - name: Upload env
        uses: actions/upload-artifact@v2
        with:
          name: env
          path: .env
      - name: Check structure
        run: |
          ls -la
  artifacts-2:
    name: Artifacts 2
    runs-on: ubuntu-20.04
    needs: [test-1]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Download env
        uses: actions/download-artifact@v2
        with:
          name: env
      - name: Add to environment variables
        run: |
          cat .env >> $GITHUB_ENV
      - name: Display value
        run: |
          echo '::notice::Env value: ${{ env.SITE_URL }}'
          ls -la

  # Second way: outputs.
  outputs-1:
    name: Outputs 1
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{steps.step1.outputs.test}}
      output2: ${{steps.step2.outputs.test}}
    steps:
      - name: Step 1
        id: step1
        run: |
          echo HELLO_ENV=hello >> $GITHUB_ENV
          echo "::set-output name=test::${{ env.HELLO_ENV }}"
      - name: Step 2
        id: step2
        run: echo "::set-output name=test::worldd"
  outputs-2:
    name: Outputs 2
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
